- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart nftables
  service:
    name: nftables
    state: restarted
  ignore_errors: "yes"
  when: '"nftables" in ansible_facts.packages'
